run_id: biis-test-001

compute:
  backend: aws-batch
  instance: g5.xlarge
  # use_spot: false

inputs:
  base: biis

pism:
  args: >
    --config {{INPUTS.base}}/biis.cfg
    --time.end 20000
    --o {{OUTPUT_DIR}}/run-{{RUN_ID}}.nc
