job_name: biis-test-001

compute:
  accelerator: gpu
  # use_spot: false

inputs:
  base: biis

pism:
  args: >
    --config {{INPUTS.base}}/biis.cfg
    --time.end 20000
    --o {{OUTPUT_DIR}}/job-{{JOB_NAME}}.nc
